# Ubuntu
FROM node:16-alpine3.16 as build-stage

EXPOSE 5000

WORKDIR /usr/app

# Copy all of the source code
COPY . .

RUN node -v && npm -v && npm install && npm run build && npm install -g serve

FROM node:16-alpine3.16
WORKDIR /usr/app
COPY --from=build-stage /usr/app/build/ /usr/app/build/
RUN node -v && npm -v && npm install -g serve && adduser appuser -D

USER appuser

# And finally the command to run the application
CMD ["serve", "-s", "-l", "5000", "build"]