# Ubuntu
FROM node:16

EXPOSE 5000

#RUN apt-get update
#RUN apt-get -y install sudo
#RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
#RUN sudo apt install -y nodejs
#RUN sudo apt install -y npm
RUN node -v && npm -v

# Copy all of the source code
COPY . .

RUN npm install

#ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm run build
RUN npm install -g serve

# And finally the command to run the application
CMD ["serve", "-s", "-l", "5000", "build"]