# Ubuntu
FROM node:16-alpine3.16 as build-stage

WORKDIR /usr/src/app
COPY . .
RUN npm ci 
ENV REACT_APP_BACKEND_URL=http://localhost:3000/
RUN CI=true npm test
RUN node -v && npm -v && npm install && npm run build && npm install -g serve

FROM node:16-alpine3.16
WORKDIR /usr/src/app
COPY --from=build-stage /usr/src/app/build/ /usr/src/app/build/
RUN node -v && npm -v && npm install -g serve && adduser appuser -D

USER appuser

CMD ["serve", "build"]
  